DROP TABLE IF EXISTS hits;

CREATE TABLE IF NOT EXISTS hits (
    id BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
    app VARCHAR(50) NOT NULL,
    uri VARCHAR(256) NOT NULL ,
    ip VARCHAR(50) NOT NULL ,
    timestamp TIMESTAMP NOT NULL,
    CONSTRAINT hits_pk PRIMARY KEY (id)
)